import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="m-4 text-yellow-400 font-bold">Header Section</div>
      <body className={inter.className}>{children}</body>
      <footer className="m-8 text-yellow-400 font-bold">Footer Section</footer>
    </html>
  );
}
