import { Inter } from "next/font/google";
import "../styles/reset.css";
import "../styles/globals.css";

import HeaderBar from '../components/header/page';
import Footer from '../components/footer/page';
import HeadComponent from './head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netfilms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HeadComponent />
      <body className={inter.className}>
        <HeaderBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}